name: Code junction build
on: 
  push:
    branches: 
      - master
  
jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
    - run: npm test 
     
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist
        path: |
            dist
            package.json
