name: Snyk Security Check

on:
  push:
    branches:
      - feature
      - master  # Change to your default branch name if needed

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

     
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
         node-version: 12.x

      - name: Install Snyk CLI
        run: npm install -g snyk@1.1237.0 

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --all-projects

      - name: Check Snyk Test Results
        run: |
          snyk_test_exit_code=$?
          if [ $snyk_test_exit_code -eq 0 ]; then
            echo "Snyk test passed, no vulnerabilities found."
          else
            echo "Snyk test failed, vulnerabilities found."
            exit 1
          fi
